/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class whoOps_RegistryRaptor */

#ifndef _Included_whoOps_RegistryRaptor
#define _Included_whoOps_RegistryRaptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     whoOps_RegistryRaptor
 * Method:    getREG_SZNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_RegistryRaptor_getREG_1SZNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_RegistryRaptor
 * Method:    setREG_SZNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_RegistryRaptor_setREG_1SZNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
