/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class whoOps_ShutdownShark */

#ifndef _Included_whoOps_ShutdownShark
#define _Included_whoOps_ShutdownShark
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     whoOps_ShutdownShark
 * Method:    rebootNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_ShutdownShark_rebootNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
