/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class whoOps_ShareshankRedemption */

#ifndef _Included_whoOps_ShareshankRedemption
#define _Included_whoOps_ShareshankRedemption
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     whoOps_ShareshankRedemption
 * Method:    getShareBeanNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_ShareshankRedemption_getShareBeanNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_ShareshankRedemption
 * Method:    getPathNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_ShareshankRedemption_getPathNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_ShareshankRedemption
 * Method:    netShareEnumNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_ShareshankRedemption_netShareEnumNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_ShareshankRedemption
 * Method:    setRemarkNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_ShareshankRedemption_setRemarkNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
