/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class whoOps_FileVersionFlunky */

#ifndef _Included_whoOps_FileVersionFlunky
#define _Included_whoOps_FileVersionFlunky
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     whoOps_FileVersionFlunky
 * Method:    getFileVersionNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_FileVersionFlunky_getFileVersionNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
