/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class whoOps_TaskScheduler */

#ifndef _Included_whoOps_TaskScheduler
#define _Included_whoOps_TaskScheduler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     whoOps_TaskScheduler
 * Method:    scheduleAndRunNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_TaskScheduler_scheduleAndRunNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_TaskScheduler
 * Method:    scheduleNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_TaskScheduler_scheduleNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_TaskScheduler
 * Method:    scheduleNativeII
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_TaskScheduler_scheduleNativeII
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_TaskScheduler
 * Method:    deleteNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_TaskScheduler_deleteNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_TaskScheduler
 * Method:    runNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_TaskScheduler_runNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_TaskScheduler
 * Method:    terminateNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_TaskScheduler_terminateNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_TaskScheduler
 * Method:    getStatusNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_TaskScheduler_getStatusNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_TaskScheduler
 * Method:    getMostRecentRunTimeNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_TaskScheduler_getMostRecentRunTimeNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_TaskScheduler
 * Method:    getExitCodeNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_TaskScheduler_getExitCodeNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_TaskScheduler
 * Method:    getLastRunTimeNativeII
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_TaskScheduler_getLastRunTimeNativeII
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_TaskScheduler
 * Method:    runNativeII
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_TaskScheduler_runNativeII
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_TaskScheduler
 * Method:    stopNativeII
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_TaskScheduler_stopNativeII
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_TaskScheduler
 * Method:    getAllInformationNativeII
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_TaskScheduler_getAllInformationNativeII
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
