/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class whoOps_ServiceMangler */

#ifndef _Included_whoOps_ServiceMangler
#define _Included_whoOps_ServiceMangler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     whoOps_ServiceMangler
 * Method:    restartNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_ServiceMangler_restartNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_ServiceMangler
 * Method:    getServiceStatusNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_ServiceMangler_getServiceStatusNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_ServiceMangler
 * Method:    stopServiceNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_ServiceMangler_stopServiceNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_ServiceMangler
 * Method:    startServiceNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_ServiceMangler_startServiceNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
