/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class whoOps_ProcessOpotamus */

#ifndef _Included_whoOps_ProcessOpotamus
#define _Included_whoOps_ProcessOpotamus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     whoOps_ProcessOpotamus
 * Method:    createProcessNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_ProcessOpotamus_createProcessNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     whoOps_ProcessOpotamus
 * Method:    createProcessIINative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_whoOps_ProcessOpotamus_createProcessIINative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
