/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class crOps_replication_JNICrOpsPusher */

#ifndef _Included_crOps_replication_JNICrOpsPusher
#define _Included_crOps_replication_JNICrOpsPusher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crOps_replication_JNICrOpsPusher
 * Method:    pushApplicationsNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_crOps_replication_JNICrOpsPusher_pushApplicationsNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
